/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */




#include "STM32f103xx_gpio_driver.h"
#include "STM32f103xx.h"



//Function declaration of delay_ms

void delay_ms(uint32_t);



// Main starts here.

int main(void)
{

	GPIO_PeriClkControl(GPIOB, ENABLE);
	GPIO_PeriClkControl(GPIOC, ENABLE);
	GPIO_PeriClkControl(GPIOA, ENABLE);

	GPIO_Handle_t redled, greenLed, blueled;

	blueled.pGPIOx = GPIOA;
	blueled.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_8;
	blueled.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_OUTPUT_2MHZ;
	blueled.GPIO_PinConfig.GPIO_PinOutInType = GPIO_OP_PP;

	GPIO_Init(&blueled);


	redled.pGPIOx = GPIOB; //GPIOB
	redled.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_11; //GPIO_PIN_NO_15;
	redled.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_OUTPUT_2MHZ;
	redled.GPIO_PinConfig.GPIO_PinOutInType = GPIO_OP_PP;

	GPIO_Init(&redled);


	greenLed.pGPIOx = GPIOC; //GPIOB
	greenLed.GPIO_PinConfig.GPIO_PinNumber = 13; //GPIO_PIN_NO_15;
	greenLed.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_OUTPUT_2MHZ;
	greenLed.GPIO_PinConfig.GPIO_PinOutInType = GPIO_OP_PP;


	GPIO_Init(&greenLed);



	while(1)
	{
		GPIO_TogglePin(GPIOC, GPIO_PIN_NO_13); // toggle led connected on PC13
		GPIO_TogglePin(GPIOB, GPIO_PIN_NO_11);
		GPIO_TogglePin(GPIOA, GPIO_PIN_NO_8);
		delay_ms(100);
	}
	return 0;

}


// Function Definition for delay_ms

void delay_ms(uint32_t ms)
{
	uint32_t delay = ms * 625;
	for (int i = 0; i < delay; i++)  // 325000 = 500 msec rough estimation
		__asm__("nop");
}

