/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

/*
 * Write a program to turn on LEDS connected to GPIOI D12, D13 and D15
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


/*
 * User defined MACROS
 */
#define RCC_BASE_ADDRESS		0x40023800									// Reset Clock Control Register Base Address
#define RCC_ABH1ENR_OFFSET		0x30										// ABH1ENR OFFSET
#define RCC_ABH1ENR_ADDRESS		(RCC_BASE_ADDRESS + RCC_ABH1ENR_OFFSET)		// ABH1ENR Register Address

#define GPIOD_BASE_ADDRESS		0x40020C00
#define GPIOD_MODEREG_OFFSET	0x00
#define GPIOD_MODEREG_ADDRESS	(GPIOD_BASE_ADDRESS + GPIOD_MODEREG_OFFSET)

#define GPIOD_ODRREG_OFFSET		0x14
#define GPIOD_ODR_ADDRESS		(GPIOD_BASE_ADDRESS + GPIOD_ODRREG_OFFSET)

int main(void)
{
	// pointer variables to hold addresses of required register to turn on led

	uint32_t *pAHB1ENR = (uint32_t *) RCC_ABH1ENR_ADDRESS;		// Peripheral Clock Enable Register pointer

	uint32_t *pGPIODMODE = (uint32_t *) GPIOD_MODEREG_ADDRESS;	// GPIOD MODE Register pointer

	uint32_t *pGPIODODR = (uint32_t *) GPIOD_ODR_ADDRESS;		// GPIOD ODR Register pointer

	// Enable the GPIOD Peripheral Clock Control bit by setting the 3rd bit in RCC AHB1ENR Register
	// Mask Value: 0x0000 0008
	// Remember, do not modify any other bit position

	*pAHB1ENR = *pAHB1ENR | 0x08;		// Set the bit 3rd without modifying other bit position

	// Configure the GPIOD Mode Register to make GPIO D12 pin as Output
	// we need to set 24th and clear 25th bit in order to make D12 pin as an OUTPUT
	// First clear the 25th and 24th bit by using AND operation
	// Mask Value for Setting 24th bit : 0x0100 0000
	// MAsk Value for clearing 25th bit: 0xFCFF FFFF

	*pGPIODMODE = *pGPIODMODE & 0xFCFFFFFF;		// GPIO D12 Mode
	*pGPIODMODE |= 0x01000000;

	*pGPIODMODE &= ~(0x3<<26);					// GPIO D13 Mode
	*pGPIODMODE |= 1UL<<26;

	*pGPIODMODE &= ~(0x3<<(15*2));				// GPIO D15 Mode
	*pGPIODMODE |= 1UL<<30;

	// Set the GPIOD12 bit in ODR register to make pin D12 high (LED ON)
	// Mask value: 0x0000 1000

	*pGPIODODR |= 0x00001000;					// Turn ON GPIO D12 Led

	*pGPIODODR |= 1UL<<13;						// Turn ON GPIO D13 Led

	*pGPIODODR |= 1UL<<15;						// Turn ON GPIO D15 Led


	//*pGPIODODR &= 0xFFFFEFFF;


    /* Loop forever */
	while(1);
}
