/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

/*
 * SPI2 Pins 		GPIO
 * --------------------------
 * NSS		-->		PB12
 * SCK		-->		PB13
 * MISO		-->		PB14
 * MOSI		-->		PB15
 *
 * Alternate Function Mode: Default
 */

#include<string.h>

#include "STM32f103xx.h"					// including target header file
#include "STM32f103xx_gpio_driver.h"
#include "STM32f103xx_SPI_driver.h"


#include <stdint.h>

/************************************************************************************
 * 								Function API Declaration
 ************************************************************************************/
void SPI2_GPIOPin_Def();		// SPI2 GPIO Pin Definition Function Declaration
void SPI2_UsrConfig();		//  SPI2 User Configuration	Function Declaration



/************************************************************************************
 * 									Main Function
 ************************************************************************************/
int main(void)
{

	char user_data[] = {"Hello Makers !"};

	// Initialize the GPIO pins for SPI2
	SPI2_GPIOPin_Def();					// SPI2 GPIO Pin Definition Setting Call

	//SPI_PeriClkControl(SPI2, ENABLE);		// Enable the SPI2 Clock Peripheral

	// Initialize the SPI2 with user configuration settings
	SPI2_UsrConfig();					// SPI2 User Configuration Call

	// Enable the Internal Slave Select (Pulled NSS signal HIGH and avoid MODF)
	SPI_SSOEConfig(SPI2,ENABLE);

	// Enable the SPI2 Peripheral
	SPI_PeriControl(SPI2,ENABLE);

	SPI_WriteData(SPI2,(uint8_t*)user_data,strlen(user_data));

	SPI_PeriControl(SPI2,DISABLE);

	return 0;
}


/************************************************************************************
 * 								Function API Definition
 ************************************************************************************/

void SPI2_GPIOPin_Def()
{
	GPIO_Handle_t SPI2Pins;

	AFIO_PeriClkControl(ENABLE);

	SPI2Pins.pGPIOx = GPIOB;
	SPI2Pins.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_OUTPUT_10MHZ;
	SPI2Pins.GPIO_PinConfig.GPIO_PinOutInType = GPIO_ALTFN_OP_PP;

	SPI2Pins.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_12;		// SPI2 NSS Pin
	GPIO_Init(&SPI2Pins);

	SPI2Pins.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_13;		// SPI2 SCK Pin
	GPIO_Init(&SPI2Pins);

	SPI2Pins.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_15;		// SPI2 MOSI pin
	GPIO_Init(&SPI2Pins);

	SPI2Pins.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_INPUT;
	SPI2Pins.GPIO_PinConfig.GPIO_PinOutInType = GPIO_IP_PUPD;
	SPI2Pins.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_14;		// SPI2 MISO  Pin
	GPIO_Init(&SPI2Pins);

	GPIO_WritePin(GPIOB, GPIO_PIN_NO_14, SET);
}

void SPI2_UsrConfig()
{
	SPI_Handle_t SPI2_UsrConfig;

	SPI2_UsrConfig.pSPIx = SPI2;
	SPI2_UsrConfig.SPI_Config.SPI_Mode = SPI_MODE_MASTER;
	SPI2_UsrConfig.SPI_Config.SPI_BusConfig = SPI_BUS_CONFIG_FD;
	SPI2_UsrConfig.SPI_Config.SPI_CLKSpeed = SPI_CLKSPEED_FPCLK_64;		// SCL Clock Speed of 125 Khz
	SPI2_UsrConfig.SPI_Config.SPI_CPHASE = SPI_CPHASE_DATA_LEAD_EDGE;
	SPI2_UsrConfig.SPI_Config.SPI_CPOL = SPI_CPOL_0_IDLE;
	SPI2_UsrConfig.SPI_Config.SPI_DataFormat = SPI_DFF_8BIT;			// Data Frame Format of 8-Bit
	SPI2_UsrConfig.SPI_Config.SPI_SlaveMgmt = SPI_SSM_DI;				// S/W Slave Management Enabled for NSS Pin

	SPI_Init(&SPI2_UsrConfig);
}

